version: "3.9"

services:
  frontend:
    build: ./front
    container_name: react_front
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./back
    container_name: spring_back
    ports:
      - "8080:8080"
